<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Midtrans\Snap;

class Midtrans
{

	public const SETTLEMENT = 'settlement';

    public function midtransSnap($data)
    {
         //Set your Merchant Server Key
         \Midtrans\Config::$serverKey = 'SB-Mid-server-6PlMJad90JImCKirfAEfbHQn';// Set to Development/Sandbox Environment (default). Set to true for Production Environment (accept real transaction).
         \Midtrans\Config::$isProduction = false;// Set sanitization on (default)
         \Midtrans\Config::$isSanitized = true;// Set 3DS transaction for credit card to true
         \Midtrans\Config::$is3ds = true;
         $params = [
            'transaction_details' => [
                'order_id' => $data['order_id'],
                'gross_amount' => $data['amount']
            ],
            'customer_details' => [
                    'first_name' => $data['atasnama'],
                    'email' => $data['email'],
                    'phone' => $data['telepon']
                ]
         ];
         if(isset($data['items'])) {
            $params['item_details'] = $data['items'];
         }
        //  dd($params);
         $snapToken = Snap::getSnapToken($params);

         return $snapToken;
    }

    public function checkTs($code_transaction)
    {
        $key = base64_encode('SB-Mid-server-6PlMJad90JImCKirfAEfbHQn');
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.midtrans.com/v2/'.$code_transaction.'/status');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'Authorization: Basic '.$key.'';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $result = curl_exec($ch);
        $json = json_decode($result);
        return $json;


    }
}
